### PR TITLE
add compiler to build requirements

### PR DESCRIPTION
**Pull request by jjhelmus**
pyopengl has compiled code and should declare the need for a c compiler.

### CODE REVIEW

**Comment by almarklein** [comment]
@conda-forge-admin, please rerender

**Comment by CJ-Wright** [comment]
@conda-forge/pyopengl thoughts?

**Comment by almarklein** [comment]
Wait, since when does PyOpenGL contains compiled code? It never did. PyOpenGL_accelerate does, but that's not what this package is about ...

**Comment by tadeu** [comment]
@jjhelmus, any comment on @almarklein remark? In Anaconda [`pyopengl-accelerate`](https://anaconda.org/anaconda/pyopengl-accelerate/files) is a different package than `pyopengl`, so if that is your intention, it could be put in a new feedstock.

Can we close this PR?

**Comment by jjhelmus** [comment]
Sorry not sure why I though this had compiled code, probably submitted this against the wrong recipe.

**Pull request closed without merging**
