### PR TITLE
install opengl

### PR DESCRIPTION
**Pull request by almarklein**
This implements option 1 in issue #1.

### CODE REVIEW

**Comment by almarklein** [comment]
@jakirkham this is what you meant, right? As a temporary solution?

**Comment by pelson** [comment]
> @jakirkham this is what you meant, right? As a temporary solution?

Agreed. In order to make this a permanent solution, @jakirkham and I both want to add extra metadata to the feedstock which informs this extra installation. At this moment in time, we are discussing exactly *where* that information should live in https://github.com/conda-forge/conda-forge.github.io/issues/82. This PR is pushing the boundary of what conda-forge can currently do, so please bear with us as we iterate! 

Thanks @almarklein!

**Comment by jakirkham** [comment]
Yes, that is what I meant.

For future reference, make sure to fork the feedstock (repo) and commit changes to a branch on your fork and PR it back here. The problem with adding changes to any branch on this repo is that those changes are automatically deployed. This is useful if you need to maintain multiple versions, but, at present, it comes at this cost of remembering this is how it works. With your fork, nothing will be deployed until it is merged back into a branch here.

**Comment by pelson** [comment]
FWIW, the accidental built binaries for linux-64 are available at https://anaconda.org/conda-forge/pyopengl/files. Turns out to be a good opportunity to test them out... 😉

**Comment by jakirkham** [comment]
Just to be clear though, there is no harm in merging this. If packages are already deployed, they will not be redeployed as we don't use force when uploading.

**Comment by almarklein** [comment]
> For future reference, make sure to fork the feedstock (repo) and commit changes to a branch on your fork and PR it back here.

Noted. It seems so nice and easy, though, to make small changes to the feedstock (e.g. increase version number) by editing via Github. I imagine that for someone maintaining dozens of packages, not having to keep local clones for each of these would be a big plus.

**Comment by jakirkham** [comment]
Absolutely, that's why I opened this issue ( https://github.com/conda-forge/conda-forge.github.io/issues/87 ). :wink: Feel free to share any thoughts you may have on this proposal.

**Comment by jakirkham** [comment]
So, this can be reverted @almarklein as we have decided to include it in the container after all. Though it will do no harm to leave it as is. Eventually when you get a conda-smithy update PR it will remove this `yum` install, but it should still pass CI. Merging that will handle both the removal of this unneeded `yum` install and an infrastructure update.

**Pull request merged**
