### PR TITLE
ADD: patch to correct issue #16

### LINKED ISSUE #16: PyOpenGL 3.1.3b2 on main breaks vispy
I have vispy travis CI jobs running weekly (with cron) and they have started failing with the newest conda-forge release of pyopengl 3.1.3b2. I created another branch that forces the version of pyopengl to 3.1.1a1 and all tests pass. The failing tests have the following error:

```
self = <OpenGL.converters.SizedOutputOrInput object at 0x2b7757b86af0>
result = None
baseOperation = <OpenGL.platform.baseplatform.glGetBufferParameteriv object at 0x2b7757b0c7e8>
pyArgs = (GL_ARRAY_BUFFER, GL_BUFFER_SIZE, <object object at 0x2b7755acf6e0>)
cArgs = (GL_ARRAY_BUFFER, GL_BUFFER_SIZE, array([192], dtype=int32))
    def oldStyleReturn( self, result, baseOperation, pyArgs, cArgs ):
        """Retrieve cArgs[ self.index ]"""
>       result = cArgs[ self.outIndex ]
E       AttributeError: ('outIndex', <bound method SizedOutputOrInput.oldStyleReturn of <OpenGL.converters.SizedOutputOrInput object at 0x2b7757b86af0>>, (None, <OpenGL.platform.baseplatform.glGetBufferParameteriv object at 0x2b7757b0c7e8>, (GL_ARRAY_BUFFER, GL_BUFFER_SIZE, <object object at 0x2b7755acf6e0>), (GL_ARRAY_BUFFER, GL_BUFFER_SIZE, array([192], dtype=int32))), {})
../../../anaconda/envs/testenv/lib/python2.7/site-packages/OpenGL/converters.py:202: AttributeError
```

You can see the failing jobs [here](https://travis-ci.org/vispy/vispy/builds/482631153) and the new succeeding jobs with 3.1.1a1 [here](https://travis-ci.org/vispy/vispy).

Any ideas? Where are these new versions coming from? I can't find a web page that has these new downloads or a source distribution on sourceforge or...anywhere.

### PR DESCRIPTION
**Pull request by kmuehlbauer**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

resolves #16

### CODE REVIEW

**Comment by kmuehlbauer** [comment]
@conda-forge-admin, please rerender

**Comment by kmuehlbauer** [comment]
Argh, @conda-forge/pyopengl Someone happen to know, why the post-link breaks?

**Comment by kmuehlbauer** [comment]
@conda-forge/core Did something change in the docker-container with regard to OpenGL (driver etc).

**Comment by ocefpaf** [comment]
> @conda-forge/core Did something change in the docker-container with regard to OpenGL (driver etc).

I'm not sure the reasons behind the change and/or if we are ready to start substituting that for a `cdt`. Meanwhile you can add something [like this](https://github.com/conda-forge/matplotlib-feedstock/blob/master/recipe/yum_requirements.txt) to get it working again.

**Comment by kmuehlbauer** [comment]
@conda-forge-admin, please rerender

**Comment by kmuehlbauer** [comment]
@ocefpaf Thanks! That did the trick. Would it be possible to pull this in? Seems, that the maintainers are currently not available. It would really help to get along downstream.

**Comment by almarklein** [comment]
Thanks for looking into this @kmuehlbauer !

**Pull request merged**
